const vscode = require('vscode');

/**
 * Activates the extension
 * @param {vscode.ExtensionContext} context
 */
function activate(context) {
    const diagnosticCollection = vscode.languages.createDiagnosticCollection('alConvention');
    context.subscriptions.push(diagnosticCollection);

    // Core validation execution logic
    const runValidation = (doc) => reviewALCode(doc, diagnosticCollection);

    context.subscriptions.push(
        vscode.workspace.onDidOpenTextDocument(runValidation),
        vscode.workspace.onDidChangeTextDocument(e => runValidation(e.document)),
        vscode.workspace.onDidCloseTextDocument(doc => diagnosticCollection.delete(doc.uri)),
        vscode.workspace.onDidChangeConfiguration(() => {
            if (vscode.window.activeTextEditor) {
                runValidation(vscode.window.activeTextEditor.document);
            }
        })
    );

    // REGISTER THE QUICK FIX PROVIDER FOR AL LANGUAGE
    context.subscriptions.push(
        vscode.languages.registerCodeActionsProvider('al', new ALActionProvider(), {
            providedCodeActionKinds: [vscode.CodeActionKind.QuickFix]
        })
    );

    if (vscode.window.activeTextEditor) {
        runValidation(vscode.window.activeTextEditor.document);
    }
}

/**
 * Custom Code Action Provider to supply Quick Fix options based on custom diagnostics
 */
class ALActionProvider {
    provideCodeActions(document, range, context, token) {
        const actions = [];
        
        // Filter diagnostics generated by our extension
        context.diagnostics
            .filter(diagnostic => diagnostic.code && diagnostic.code.toString().startsWith('AL_CONV_'))
            .forEach(diagnostic => {
                // If a suggested fix string was bundled with the diagnostic, create a Quick Fix action
                if (diagnostic.suggestedFix) {
                    const fixAction = new vscode.CodeAction(
                        `Rename to '${diagnostic.suggestedFix}' (AL Convention)`, 
                        vscode.CodeActionKind.QuickFix
                    );
                    
                    // Create a workspace edit to swap the invalid text with the fix
                    const edit = new vscode.WorkspaceEdit();
                    edit.replace(document.uri, diagnostic.range, diagnostic.suggestedFix);
                    fixAction.edit = edit;
                    
                    // Automatically mark it as the preferred fix option
                    fixAction.isPreferred = true;
                    actions.push(fixAction);
                }
            });
            
        return actions;
    }
}

/**
 * Helper to transform an arbitrary string to snake_case safely
 */
function toSnakeCase(str) {
    return str
        .replace(/([a-z0-9])([A-Z])/g, '$1_$2') // Handle camel/Pascal case boundaries
        .replace(/[^a-zA-Z0-9_]/g, '')         // Strip special characters
        .toLowerCase();
}

function checkNamingStyle(str, style) {
    if (!str) return true;
    switch (style) {
        case 'snake_case':
            return /^[a-z0-9]+(_[a-z0-9]+)*$/.test(str);
        case 'camelCase':
            return /^[a-z0-9]+([A-Z0-9][a-z0-9]*)*$/.test(str);
        case 'PascalCase':
            return /^[A-Z0-9][a-z0-9]*([A-Z0-9][a-z0-9]*)*$/.test(str);
        default:
            return true;
    }
}

/**
 * Main logic reviewing AL convention and embedding Quick Fix payloads
 */
function reviewALCode(document, collection) {
    if (document.languageId !== 'al') { return; }

    const diagnostics = [];
    const text = document.getText();

    const config = vscode.workspace.getConfiguration('alConvention');
    const objectPrefix = config.get('objectPrefix') || 'ATL_';
    const tempConfigPrefix = config.get('temporaryPrefix') !== undefined ? config.get('temporaryPrefix') : 'temp';
    const typeMapping = config.get('typeMapping') || {};
    const namingStyles = config.get('namingStyles') || {};

    const tempMiddleFix = tempConfigPrefix ? `${tempConfigPrefix}_` : '';
    const getShortType = (fullType) => {
        return typeMapping[fullType] || typeMapping[fullType.charAt(0).toUpperCase() + fullType.slice(1).toLowerCase()] || fullType.toLowerCase().substring(0, 3);
    };

    // -------------------------------------------------------------------------
    // 1. OBJECT NAME VALIDATION & QUICK FIX
    // -------------------------------------------------------------------------
    const objectRegex = /^(table|page|codeunit|report|query|xmlport|tableextension|pageextension)\s+\d+\s+([a-zA-Z0-9_"]+)/gm;
    let match;
    while ((match = objectRegex.exec(text)) !== null) {
        let objName = match[2].replace(/"/g, '');
        if (!objName.startsWith(objectPrefix)) {
            const suggestedFix = objectPrefix + objName; // e.g., MyCodeunit -> ATL_MyCodeunit
            createDiagnostic(match, objName, `Object name '${objName}' must start with '${objectPrefix}'`, document, diagnostics, 'AL_CONV_OBJ', suggestedFix);
        }
    }

    // -------------------------------------------------------------------------
    // 2. PROCEDURE NAME VALIDATION & QUICK FIX
    // -------------------------------------------------------------------------
    const procRegex = /(?:local\s+|internal\s+)?procedure\s+([a-zA-Z0-9_]+)\(/gm;
    const procStyle = namingStyles['procedure'] || 'snake_case';
    while ((match = procRegex.exec(text)) !== null) {
        const procName = match[1];
        if (!checkNamingStyle(procName, procStyle)) {
            // Generates alternative if team uses snake_case rule
            const suggestedFix = procStyle === 'snake_case' ? toSnakeCase(procName) : procName;
            createDiagnostic(match, procName, `Procedure name '${procName}' must comply with ${procStyle}`, document, diagnostics, 'AL_CONV_PROC', suggestedFix !== procName ? suggestedFix : null);
        }
    }

    // -------------------------------------------------------------------------
    // 3. PARAMETER VALIDATION & QUICK FIX
    // -------------------------------------------------------------------------
    const paramBlockRegex = /procedure\s+[a-zA-Z0-9_]+\(([^)]*)\)/gm;
    const paramStyle = namingStyles['parameter'] || 'snake_case';
    while ((match = paramBlockRegex.exec(text)) !== null) {
        const paramBlock = match[1];
        if (!paramBlock.trim()) continue;

        const params = paramBlock.split(';');
        params.forEach(param => {
            const parts = param.split(':');
            if (parts.length === 2) {
                let pName = parts[0].replace(/var\s+/i, '').trim();
                let fullTypeString = parts[1].trim();
                
                const isTemp = /\btemporary\b/i.test(fullTypeString);
                let pType = fullTypeString.split(' ')[0].split('[')[0].replace(/"/g, '');

                const shortType = getShortType(pType);
                const expectedPrefix = isTemp ? `p${tempMiddleFix}${shortType}_` : `p${shortType}_`;
                
                let cleanBase = pName;
                if (pName.startsWith(expectedPrefix)) {
                    cleanBase = pName.substring(expectedPrefix.length);
                } else {
                    // Strip arbitrary prefixes if present before converting base name
                    cleanBase = pName.replace(/^(p[a-z]*_)/, '');
                }

                const formattedBase = paramStyle === 'snake_case' ? toSnakeCase(cleanBase) : cleanBase;
                const suggestedFix = expectedPrefix + formattedBase;

                if (pName !== suggestedFix) {
                    const startOffset = match.index + match[0].indexOf(pName);
                    const range = new vscode.Range(document.positionAt(startOffset), document.positionAt(startOffset + pName.length));
                    const diag = new vscode.Diagnostic(range, `AL Convention: Parameter '${pName}' must use format '${expectedPrefix}${paramStyle}'`, vscode.DiagnosticSeverity.Warning);
                    diag.code = 'AL_CONV_PARAM';
                    diag.suggestedFix = suggestedFix;
                    diagnostics.push(diag);
                }
            }
        });
    }

    // -------------------------------------------------------------------------
    // 4. LOCAL & GLOBAL VARIABLES VALIDATION & QUICK FIX
    // -------------------------------------------------------------------------
    const lines = text.split('\n');
    const localVarStyle = namingStyles['local_variable'] || 'snake_case';
    const globalVarStyle = namingStyles['global_variable'] || 'snake_case';

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        const varMatch = /^\s*([a-zA-Z0-9_]+)\s*:\s*([a-zA-Z0-9_\[\]" ]+)/.exec(line);
        
        if (varMatch) {
            const vName = varMatch[1];
            const fullTypeString = varMatch[2].trim();
            const vType = fullTypeString.split(' ')[0].split('[')[0].replace(/"/g, '');
            const shortType = getShortType(vType);

            let isTemp = /\btemporary\b/i.test(line);
            if (!isTemp && i + 1 < lines.length) {
                if (/^\s*IsTemporary\s*=\s*true\s*;/i.test(lines[i + 1])) {
                    isTemp = true;
                }
            }

            const isLocal = line.search(/\S/) > 4; 
            const prefixChar = isLocal ? 'l' : 'g';
            const currentStyle = isLocal ? localVarStyle : globalVarStyle;
            
            const expectedPrefix = isTemp ? `${prefixChar}${tempMiddleFix}${shortType}_` : `${prefixChar}${shortType}_`;
            
            let cleanBase = vName;
            if (vName.startsWith(expectedPrefix)) {
                cleanBase = vName.substring(expectedPrefix.length);
            } else {
                cleanBase = vName.replace(/^([lg][a-z]*_)/, '');
            }

            const formattedBase = currentStyle === 'snake_case' ? toSnakeCase(cleanBase) : cleanBase;
            const suggestedFix = expectedPrefix + formattedBase;

            if (vName !== suggestedFix) {
                const startChar = line.indexOf(vName);
                const range = new vscode.Range(new vscode.Position(i, startChar), new vscode.Position(i, startChar + vName.length));
                const diag = new vscode.Diagnostic(range, `AL Convention: Variable '${vName}' must use format '${expectedPrefix}${currentStyle}'`, vscode.DiagnosticSeverity.Warning);
                diag.code = 'AL_CONV_VAR';
                diag.suggestedFix = suggestedFix;
                diagnostics.push(diag);
            }
        }
    }

    collection.set(document.uri, diagnostics);
}

/**
 * Centralized structural setup for convention diagnostics
 */
function createDiagnostic(match, targetString, message, document, diagnostics, code, suggestedFix = null) {
    const startPos = document.positionAt(match.index + match[0].indexOf(targetString));
    const endPos = document.positionAt(match.index + match[0].indexOf(targetString) + targetString.length);
    const range = new vscode.Range(startPos, endPos);
    const diagnostic = new vscode.Diagnostic(range, `AL Convention: ${message}`, vscode.DiagnosticSeverity.Warning);
    
    diagnostic.code = code;
    if (suggestedFix) {
        diagnostic.suggestedFix = suggestedFix; // Embed suggestion to read later in the ActionProvider
    }
    
    diagnostics.push(diagnostic);
}

function deactivate() {}

module.exports = { activate, deactivate };